// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/common/visitHistory/{Wearable_SN}{start_date}{end_date}": {
            "get": {
                "description": "테스트용 작성후 삭제예정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "app working test",
                "operationId": "Wearable_SN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wearable_SN",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "start_date",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "end_date",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.UserLogModel"
                        }
                    }
                }
            }
        },
        "/v1/kiosk/checksn/{wearableSN}": {
            "get": {
                "description": "Wearable SN를 받아 사용하는 유저가 존재하는지 확인하는 기능",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kiosk"
                ],
                "summary": "check Wearable SN",
                "operationId": "userCheck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wearable Serial Number",
                        "name": "sn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kiosk.UserCheckModel"
                        }
                    }
                }
            }
        },
        "/v1/kiosk/welcome/{name}": {
            "get": {
                "description": "테스트용 작성후 삭제예정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kiosk"
                ],
                "summary": "kiosk working test",
                "operationId": "hello",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kiosk.UserLogModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.UserLogModel": {
            "type": "object",
            "properties": {
                "Date": {
                    "type": "string",
                    "example": "2021-06-30"
                },
                "IDX": {
                    "type": "integer",
                    "format": "int64",
                    "example": 1
                },
                "Time": {
                    "type": "string",
                    "example": "15:30:30"
                },
                "building_name": {
                    "type": "string"
                },
                "temp": {
                    "type": "string",
                    "example": "36.5"
                }
            }
        },
        "kiosk.UserCheckModel": {
            "type": "object",
            "properties": {
                "isuser": {
                    "type": "boolean",
                    "example": true
                },
                "wearableSN": {
                    "type": "string",
                    "example": "wsn1111"
                }
            }
        },
        "kiosk.UserLogModel": {
            "type": "object",
            "properties": {
                "Kiosk_SN": {
                    "type": "string"
                },
                "Wearable_SN": {
                    "type": "string",
                    "example": "wsn1111"
                },
                "date": {
                    "type": "string",
                    "example": "2021-05-16"
                },
                "temp": {
                    "type": "number",
                    "format": "float64",
                    "example": 36.5
                },
                "time": {
                    "type": "string",
                    "example": "03:14:18"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "NFC API",
	Description: "Hoseo NFC 2021 projct API Page",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
