FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY NFC_kafka_consumer.py ./
COPY Consumer-init.json ./

CMD ["python", "./NFC_kafka_consumer.py"]